kind: pipeline
type: docker
name: frontend_dev

steps:
  - name: lint&test
    image: node
    commands:
      - npm install
      - npm run lint
  
  - name: build image
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      username: 
        from_secret: ssh_name
      key:
        from_secret: ssh_key
      port: 22
      timeout: 60s
      command_timeout: 2m
      script:
        - cd datadrive/apps/smalldidiUrl
        - git checkout dev
        - git pull
        - sudo docker build -f docker/dockerfile . -t backend:1.0
        - cd ~/datadrive/nginx
        - sudo docker-compose -f docker-compose.yml up -d 

trigger:
  branch:
    - dev
  event:
    - push