version: '3'
services:
    backend:
      build:
        context: ../
        dockerfile: docker/dockerfile
      image: backend:1.0
      ports:
        - 5000:5000
      depends_on:
        - mongo
      environment:
        MONGO_URI: mongodb://mongo:27017

    mongo:
      image: mongo
      volumes:
        - ./data/db:/data/db
      ports:
        - 27017:27017
      restart: always


